# nginx proxy address - http://172.17.0.1:8087

name: privatebin
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    pull_policy: always
    container_name: privatebin-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - privatebin
    ports:
      - "172.17.0.1:8087:8080"
    environment:
      TZ: ${TZ:-America/New_York}
      PHP_TZ: ${TZ:-America/New_York}
    volumes:
      - ./volumes/config/privatebin:/srv/cfg
      - ./volumes/data/privatebin:/srv/data

networks:
  privatebin:
    name: privatebin
    external: false
